<?php defined('SYSPATH') or die('No direct script access.');

class Controller_Client_UserState extends AC_Controller
{

	public $auto_render  = false;


	public function action_read(){

		$data = array('id' => 3,

							'visibleFarmLeftButs' => array(1, 2, 3),
							'visibleFarmRightButs' => array(1, 2, 3),
							'visiblefarmGroupsButs' => array(1, 2, 3),
							'visiblefarmNamesButs' => array(1, 2, 3),
							'blockSettingsFarm' => array(1, 2),
							'checkedFarmGroups' => array(),
							'checkedFarmNames' => array(),
							'expandedFarmGroups' => array(),

							'visibleContragentLeftButs' => array(1, 2, 3),
							'visibleContragentRightButs' => array(1, 2, 3),
							'visiblecontragentGroupsButs' => array(1, 2, 3),
							'visiblecontragentNamesButs' => array(1, 2, 3),
							'blockSettingsContragent' => array(1, 2),
							'checkedContragentGroups' => array(),
							'checkedContragentNames' => array(),
							'expandedContragentGroups' => array(),

							'visibleSeedLeftButs' => array(1, 2, 3),
							'visibleSeedRightButs' => array(1, 2, 3),
							'visibleseedGroupsButs' => array(1, 2, 3),
							'visibleseedNamesButs' => array(1, 2, 3),
							'visibleseedSubnamesButs' => array(1, 2, 3),
							'blockSettingsSeed' => array(1, 2),
							'checkedSeedGroups' => array(),
							'checkedSeedNames' => array(),
							'checkedSeedSubnames' =>  array(),
							'expandedSeedGroups' => array(),

							'visibleProductionLeftButs' => array(1, 2, 3),
							'visibleProductionRightButs' => array(1, 2, 3),
							'visibleproductionGroupsButs' => array(1, 2, 3),
							'visibleproductionNamesButs' => array(1, 2, 3),
							'visibleproductionSubnamesButs' => array(1, 2, 3),
							'blockSettingsProduction' => array(1, 2),
							'checkedProductionGroups' => array(),
							'checkedProductionNames' => array(),
							'checkedProductionSubnames' =>  array(),
							'expandedProductionGroups' => array(),

							'visibleCultureLeftButs' => array(1, 2, 3),
							'visibleCultureRightButs' => array(1, 2, 3),
							'visiblecultureGroupsButs' => array(1, 2, 3),
							'visiblecultureNamesButs' => array(1, 2, 3),
							'blockSettingsCulture' => array(1, 2),
							'checkedCultureGroups' => array(),
							'checkedCultureNames' => array(),
							'expandedCultureGroups' => array(),

							'visibleGsmLeftButs' => array(1, 2, 3),
							'visibleGsmRightButs' => array(1, 2, 3),
							'visiblegsmGroupsButs' => array(1, 2, 3),
							'visiblegsmNamesButs' => array(1, 2, 3),
							'blockSettingsGsm' => array(1, 2),
							'checkedGsmGroups' => array(),
							'checkedGsmNames' => array(),
							'expandedGsmGroups' => array(),

							'visibleSzrLeftButs' => array(1, 2, 3),
							'visibleSzrRightButs' => array(1, 2, 3),
							'visibleszrGroupsButs' => array(1, 2, 3),
							'visibleszrNamesButs' => array(1, 2, 3),
							'blockSettingsSzr' => array(1, 2),
							'checkedSzrGroups' => array(),
							'checkedSzrNames' => array(),
							'expandedSzrGroups' => array(),

							'visibleSzrtargetLeftButs' => array(1, 2, 3),
							'visibleSzrtargetRightButs' => array(1, 2, 3),
							'visibleszrtargetGroupsButs' => array(1, 2, 3),
							'visibleszrtargetNamesButs' => array(1, 2, 3),
							'blockSettingsSzrtarget' => array(1, 2),
							'checkedSzrtargetGroups' => array(),
							'checkedSzrtargetNames' => array(),
							'expandedSzrtargetGroups' => array(),

							'visibleSzrdvLeftButs' => array(1, 2, 3),
							'visibleSzrdvRightButs' => array(1, 2, 3),
							'visibleszrdvGroupsButs' => array(1, 2, 3),
							'visibleszrdvNamesButs' => array(1, 2, 3),
							'blockSettingsSzrdv' => array(1, 2),
							'checkedSzrdvGroups' => array(),
							'checkedSzrdvNames' => array(),
							'expandedSzrdvGroups' => array(),

							'visibleFertilizerLeftButs' => array(1, 2, 3),
							'visibleFertilizerRightButs' => array(1, 2, 3),
							'visiblefertilizerGroupsButs' => array(1, 2, 3),
							'visiblefertilizerNamesButs' => array(1, 2, 3),
							'blockSettingsFertilizer' => array(1, 2),
							'checkedFertilizerGroups' => array(),
							'checkedFertilizerNames' => array(),
							'expandedFertilizerGroups' => array(),

							'visibleFertilizertargetLeftButs' => array(1, 2, 3),
							'visibleFertilizertargetRightButs' => array(1, 2, 3),
							'visiblefertilizertargetGroupsButs' => array(1, 2, 3),
							'visiblefertilizertargetNamesButs' => array(1, 2, 3),
							'blockSettingsFertilizertarget' => array(1, 2),
							'checkedFertilizertargetGroups' => array(),
							'checkedFertilizertargetNames' => array(),
							'expandedFertilizertargetGroups' => array(),

							'visibleFertilizerdvLeftButs' => array(1, 2, 3),
							'visibleFertilizerdvRightButs' => array(1, 2, 3),
							'visiblefertilizerdvGroupsButs' => array(1, 2, 3),
							'visiblefertilizerdvNamesButs' => array(1, 2, 3),
							'blockSettingsFertilizerdv' => array(1, 2),
							'checkedFertilizerdvGroups' => array(),
							'checkedFertilizerdvNames' => array(),
							'expandedFertilizerdvGroups' => array(),

							'visiblepredecessorGroupsButs' => array(1, 2, 3),
							'visiblepredecessorNamesButs' => array(1, 2, 3),
							'visiblePredecessorLeftButs' => array(1, 2, 3),
							'visiblePredecessorRightButs' => array(1, 2, 3),
							'blockSettingsPredecessor' => array(1, 2),
							'checkedPredecessorGroups' => array(),
							'checkedPredecessorNames' => array(),
							'expandedPredecessorGroups' => array(),

							'visibleMobileLeftButs' => array(1, 2, 3),
							'visibleMobileRightButs' => array(1, 2, 3),
							'visiblemobileGroupsButs' => array(1, 2, 3),
							'visiblemobileNamesButs' => array(1, 2, 3),
							'blockSettingsMobile' => array(1, 2),
							'checkedMobileGroups' => array(),
							'checkedMobileNames' => array(),
							'expandedMobileGroups' => array(),

							'visibleTrailerLeftButs' => array(1, 2, 3),
							'visibleTrailerRightButs' => array(1, 2, 3),
							'visibletrailerGroupsButs' => array(1, 2, 3),
							'visibletrailerNamesButs' => array(1, 2, 3),
							'blockSettingsTrailer' => array(1, 2),
							'checkedTrailerGroups' => array(),
							'checkedTrailerNames' => array(),
							'expandedTrailerGroups' => array(),

							'visibleUnitsLeftButs' => array(1, 2, 3),
							'visibleUnitsRightButs' => array(1, 2, 3),
							'visibleUnitsGroupsButs' => array(1, 2, 3),
							'visibleUnitsNamesButs' => array(1, 2, 3),
							'blockSettingsUnits' => array(1, 2),
							'checkedUnitsGroups' => array(),
							'checkedUnitsNames' => array(),
							'expandedUnitsGroups' => array(),

							'visiblePeriodGroupsButs' => array(1, 2, 3),
//							'visiblePeriodNamesButs' => array(1, 2, 3),
							'visiblePeriodLeftButs' => array(1, 2, 3),
							'visiblePeriodRightButs' => array(1, 2, 3),
							'blockSettingsPeriod' => array(1, 2),
							'checkedPeriodGroups' => array(),
//							'checkedPeriodNames' => array(),
							'expandedPeriodGroups' => array(),

							'visiblePersonalGroupsButs' => array(1, 2, 3),
							'visiblePersonalNamesButs' => array(1, 2, 3),
							'visiblePersonalLeftButs' => array(1, 2, 3),
							'visiblePersonalRightButs' => array(1, 2, 3),
							'blockSettingsPersonal' => array(1, 2),
							'checkedPersonalGroups' => array(),
							'checkedPersonalNames' => array(),
							'expandedPersonalGroups' => array(),

							'visibleMapLeftButs' => array(1, 2, 3),
							'visibleMapRightButs' => array(1, 2, 3),
							'visiblemapGroupsButs' => array(1, 2, 3),
							'visiblemapNamesButs' => array(1, 2, 3),
							'blockSettingsMap' => array(1, 2),
							'checkedMapGroupsLeft' => array(),
							'checkedMapGroupsRight' => array(),
							'checkedMapNames' => array(),
							'expandedMapGroups' => array(),

							'visibleCountryGroupsButs' => array(1, 2, 3),
							'visibleCountryNamesButs' => array(1, 2, 3),
							'visibleCountryLeftButs' => array(1, 2, 3),
							'visibleCountryRightButs' => array(1, 2, 3),
							'blockSettingsCountry' => array(1, 2),
							'checkedCountryGroups' => array(),
							'checkedCountryNames' => array(),
							'expandedCountryGroups' => array(),

							'visibleProducerGroupsButs' => array(1, 2, 3),
							'visibleProducerNamesButs' => array(1, 2, 3),
							'visibleProducerLeftButs' => array(1, 2, 3),
							'visibleProducerRightButs' => array(1, 2, 3),
							'blockSettingsProducer' => array(1, 2),
							'checkedProducerGroups' => array(),
							'checkedProducerNames' => array(),
							'expandedProducerGroups' => array(),

							'visibleChemicalElementsGroupsButs' => array(1, 2, 3),
							'visibleChemicalElementsNamesButs' => array(1, 2, 3),
							'visibleChemicalElementsLeftButs' => array(1, 2, 3),
							'visibleChemicalElementsRightButs' => array(1, 2, 3),
							'blockSettingsChemicalElements' => array(1, 2),
							'checkedChemicalElementsGroups' => array(),
							'checkedChemicalElementsNames' => array(),
							'expandedChemicalElementsGroups' => array(),

							'visibleHandbookPersonalGroupsButs' => array(1, 2, 3),
							'visibleHandbookPersonalNamesButs' => array(1, 2, 3),
							'visibleHandbookPersonalLeftButs' => array(1, 2, 3),
							'visibleHandbookPersonalRightButs' => array(1, 2, 3),
							'blockSettingsHandbookPersonal' => array(1, 2),
							'checkedHandbookPersonalGroups' => array(),
							'checkedHandbookPersonalNames' => array(),
							'expandedHandbookPersonalGroups' => array(),

							'visibleHandbookTechniqueMobileGroupsButs' => array(1, 2, 3),
							'visibleHandbookTechniqueMobileNamesButs' => array(1, 2, 3),
							'visibleHandbookTechniqueMobileLeftButs' => array(1, 2, 3),
							'visibleHandbookTechniqueMobileRightButs' => array(1, 2, 3),
							'blockSettingsHandbookTechniqueMobile' => array(1, 2),
							'checkedHandbookTechniqueMobileGroups' => array(),
							'checkedHandbookTechniqueMobileNames' => array(),
							'expandedHandbookTechniqueMobileGroups' => array(),

							'visibleHandbookTechniqueTrailerGroupsButs' => array(1, 2, 3),
							'visibleHandbookTechniqueTrailerNamesButs' => array(1, 2, 3),
							'visibleHandbookTechniqueTrailerLeftButs' => array(1, 2, 3),
							'visibleHandbookTechniqueTrailerRightButs' => array(1, 2, 3),
							'blockSettingsHandbookTechniqueTrailer' => array(1, 2),
							'checkedHandbookTechniqueTrailerGroups' => array(),
							'checkedHandbookTechniqueTrailerNames' => array(),
							'expandedHandbookTechniqueTrailerGroups' => array(),

							'visibleDeploymentTypeLeftButs' => array(1, 2, 3),
							'visibleDeploymentTypeRightButs' => array(1, 2, 3),
							'visibledeploymenttypeNamesButs' => array(1, 2, 3),
							'blockSettingsDeploymentType' => array(1, 2),
							'checkedDeploymentTypeNames' => array(),

							'visibleSzrDeploymentTypeLeftButs' => array(1, 2, 3),
							'visibleSzrDeploymentTypeRightButs' => array(1, 2, 3),
							'visibleszrdeploymenttypeNamesButs' => array(1, 2, 3),
							'blockSettingsSzrDeploymentType' => array(1, 2),
							'checkedSzrDeploymentTypeNames' => array(),

							'visibleFertilizerDeploymentTypeLeftButs' => array(1, 2, 3),
							'visibleFertilizerDeploymentTypeRightButs' => array(1, 2, 3),
							'visiblefertilizerdeploymenttypeNamesButs' => array(1, 2, 3),
							'blockSettingsFertilizerDeploymentType' => array(1, 2),
							'checkedFertilizerDeploymentTypeNames' => array(),

                            'blockSettingsOperationstages' => array(1, 2),
							'checkedOperationstagesGroups' => array(),
							'checkedOperationstagesNames' => array(),
							'expandedOperationstagesGroups' => array(),

                            'blockSettingsOperations' => array(1, 2),
							'checkedOperationsGroups' => array(),
							'checkedOperationsNames' => array(),
							'expandedOperationsGroups' => array(),

                            'blockSettingsAtk' => array(1, 2),
							'checkedAtkGroups' => array(),
							'checkedAtkNames' => array(),
							'expandedAtkGroups' => array(),
                            'atkTableView' => FALSE,
			
							'blockSettingsShare' => array(1, 2),

							'visiblePlanningHandbookVersionsNamesButs' => array(1, 2, 3),
							'visiblePlanningHandbookVersionsLeftButs' => array(1, 2, 3),
							'visiblePlanningHandbookVersionsRightButs' => array(1, 2, 3),
							'blockSettingsPlanningHandbookVersions' => array(1, 2),
							'checkedPlanningHandbookVersionsNames' => array(),
            
                            'visibleChemicalCompositionLeftButs' => array(1, 2, 3),
							'visibleChemicalCompositionRightButs' => array(1, 2, 3),
							'visibleChemicalCompositionGroupsButs' => array(1, 2, 3),
							'visibleChemicalCompositionNamesButs' => array(1, 2, 3),
							'blockSettingsChemicalComposition' => array(1, 2),
							'checkedChemicalCompositionGroups' => array(),
							'checkedChemicalCompositionNames' => array(),
							'expandedChemicalCompositionGroups' => array(),

							'glossaryInterfaceCulturesMinimized' => array(),
							'glossaryMinimized' => false,
							'settingsInterfaceDepartmentsMinimized' => array(),
							'settingsMinimized' => false);

		$this->request->response = json_encode($data);
	}


	public function action_update(){
		$this->request->response = true;
	}

}
